name: Testes Selenium

on: [push, pull_request]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - name: Configurar Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Executar todas as questões
        run: mvn --batch-mode test